// flow-typed signature: 8834c192c626e4da85bb745d58d85fc0
// flow-typed version: <<STUB>>/big.js_v^5.1.2/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'big.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'big.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'big.js/big' {
  declare module.exports: any;
}

declare module 'big.js/big.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'big.js/big.js' {
  declare module.exports: $Exports<'big.js/big'>;
}
declare module 'big.js/big.min.js' {
  declare module.exports: $Exports<'big.js/big.min'>;
}
